// Generated by wxt
export {}
declare global {
  const CONFIG: typeof import('/workspace/openthatlink/apps/extension/utils/config')['CONFIG']
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const MigrationError: typeof import('wxt/storage')['MigrationError']
  const browser: typeof import('wxt/browser')['browser']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const defineAppConfig: typeof import('wxt/sandbox')['defineAppConfig']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const disableTurboMode: typeof import('/workspace/openthatlink/apps/extension/utils/storage')['disableTurboMode']
  const enableTurboMode: typeof import('/workspace/openthatlink/apps/extension/utils/storage')['enableTurboMode']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const generateSecret: typeof import('/workspace/openthatlink/apps/extension/utils/secret')['generateSecret']
  const getExtensionConfig: typeof import('/workspace/openthatlink/apps/extension/utils/storage')['getExtensionConfig']
  const getOrCreateSecret: typeof import('/workspace/openthatlink/apps/extension/utils/storage')['getOrCreateSecret']
  const getPollUrl: typeof import('/workspace/openthatlink/apps/extension/utils/secret')['getPollUrl']
  const getStoredBaseUrl: typeof import('/workspace/openthatlink/apps/extension/utils/storage')['getStoredBaseUrl']
  const getStoredSecret: typeof import('/workspace/openthatlink/apps/extension/utils/storage')['getStoredSecret']
  const getTurboEndTime: typeof import('/workspace/openthatlink/apps/extension/utils/storage')['getTurboEndTime']
  const getWebhookUrl: typeof import('/workspace/openthatlink/apps/extension/utils/secret')['getWebhookUrl']
  const injectScript: typeof import('wxt/client')['injectScript']
  const isTurboModeActive: typeof import('/workspace/openthatlink/apps/extension/utils/storage')['isTurboModeActive']
  const regenerateSecret: typeof import('/workspace/openthatlink/apps/extension/utils/storage')['regenerateSecret']
  const resetBaseUrl: typeof import('/workspace/openthatlink/apps/extension/utils/storage')['resetBaseUrl']
  const storage: typeof import('wxt/storage')['storage']
  const storeBaseUrl: typeof import('/workspace/openthatlink/apps/extension/utils/storage')['storeBaseUrl']
  const storeSecret: typeof import('/workspace/openthatlink/apps/extension/utils/storage')['storeSecret']
  const useAppConfig: typeof import('wxt/client')['useAppConfig']
  const validateSecret: typeof import('/workspace/openthatlink/apps/extension/utils/secret')['validateSecret']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Config } from '/workspace/openthatlink/apps/extension/utils/config'
  import('/workspace/openthatlink/apps/extension/utils/config')
  // @ts-ignore
  export type { ExtensionConfig } from '/workspace/openthatlink/apps/extension/utils/storage'
  import('/workspace/openthatlink/apps/extension/utils/storage')
}
